# This file was generated by GoReleaser. DO NOT EDIT.
class Gum < Formula
  desc "Gum is a Gradle/Maven wrapper written in Go"
  homepage "https://github.com/kordamp/gm"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kordamp/gm/releases/download/v0.3.0/gm_Darwin_x86_64.zip"
    sha256 "e6d3b56048051cd294a81ac82e54b2ecec0214b332136595d72f5b087df60fea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kordamp/gm/releases/download/v0.3.0/gm_Linux_x86_64.tar.gz"
      sha256 "d6eea85c0a7b0a25907bb757173c940d96c9f2a59a96272eba4efbe5e142afde"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kordamp/gm/releases/download/v0.3.0/gm_Linux_arm64.tar.gz"
        sha256 "9e4750eab92630ca0a7e68ab68f20b3504ab18ddf98551d666400e52210387dd"
      else
        url "https://github.com/kordamp/gm/releases/download/v0.3.0/gm_Linux_armv6.tar.gz"
        sha256 "5c77554ac34eb609d9b4da569a393cce5134b2c5c8131a5a7545edba1ea64bae"
      end
    end
  end

  def install
    bin.install "gm"
  end
end
